// Generated by CoffeeScript 1.6.3
(function() {
  var SpacesTabs;

  SpacesTabs = (function() {
    function SpacesTabs(name) {
      this.name = name;
    }

    SpacesTabs.prototype.hi = function() {};

    SpacesTabs.prototype.hi2 = function() {};

    SpacesTabs.prototype.say = function() {
      return {
        say2: function() {}
      };
    };

    SpacesTabs.prototype.m1 = function() {};

    SpacesTabs.prototype.m2 = function() {
      return {
        m2: function() {},
        m3: function() {},
        m3: function() {}
      };
    };

    SpacesTabs.prototype.bye = function() {};

    SpacesTabs.prototype.bye = function() {};

    return SpacesTabs;

  })();

}).call(this);
